-- return {
--   "akinsho/toggleterm.nvim",
--   enable = false,
--   version = "*",
--   -- keys = {
--   --   { "n", "<C-t>", "<cmd>ToggleTerm size=40 dir=${workspaceFolder} direction=float" },
--   -- },
--   opts = {
--     open_mapping = [[<c-\>]],
--     shade_terminals = true, -- NOTE: this option takes priority over highlights specified so if you specify Normal highlights you should set this to false
--     -- shading_factor = "<number>", -- the percentage by which to lighten terminal background, default: -30 (gets multiplied by -3 if background is light)
--     start_in_insert = true,
--     insert_mappings = true, -- whether or not the open mapping applies in insert mode
--     terminal_mappings = true, -- whether or not the open mapping applies in the opened terminals
--     persist_size = true,
--     persist_mode = true, -- if set to true (default) the previous terminal mode will be remembered
--     direction = "float",
--     close_on_exit = true, -- close the terminal window when the process exits
--     shell = vim.o.shell, -- change the default shell
--     auto_scroll = true,
--     autochdir = true,
--   },
-- }
